src/SPECK2D.cpp
src/SPECK3D.cpp
src/SPECK_Storage.cpp
src/SPERR.cpp
src/sperr_helper.cpp
src/sperr_helper.h

Helper functions would require callers to allocate memory

---

CMakeLists.txt
test_scripts/CMakeLists.txt
utilities/CMakeLists.txt

Put utilities and test_scripts CMakeLists.txt to their own directories

---

CMakeLists.txt
SperrConfig.h.in
src/SPECK3D_OMP_C.cpp
src/SPECK3D_OMP_D.cpp
utilities/CMakeLists.txt
utilities/show_version.cpp

implement show_version utility

---

CMakeLists.txt
test_scripts/speck3d_unit_test.cpp

Also conditional compilation of utility programs.

Select GTest Version

---

src/SPECK3D.cpp
src/sperr_helper.cpp

Some minor changes from the meetup :+1:

North Devner C++ Meetup

---

src/SPECK3D.cpp
src/sperr_helper.cpp

This PR applies a few enhancements to PR #124.

minor fixes on PR #124

---

CMakeLists.txt
examples/C_API/2d_qz.c
examples/C_API/3d_qz.c
examples/C_API/Makefile
examples/C_API/test.c
include/SPECK2D_Compressor.h
include/SPECK2D_Decompressor.h
include/SPECK3D_Compressor.h
include/SPERR_C_API.h
src/CMakeLists.txt
src/SPERR_C_API.cpp
utilities/compressor_2d.cpp
utilities/show_version.cpp

This PR implements the simplest C API. It provides functions for 2D and 3D compression and decompression in fixed-error mode.
API not implemented here are ones with domain decomposition, and ones with fixed-size mode.

C API, step 1

---

include/CDF97.h
include/SPECK2D.h
include/SPECK3D.h
include/SPECK_Storage.h
src/SPECK2D.cpp
src/SPECK2D_Compressor.cpp
src/SPECK3D.cpp
src/SPECK3D_Compressor.cpp
src/SPECK_Storage.cpp

minor changes, mostly a variable name update. Also removed some unnecessary [[noregard]] notations.

function and variable name change

---

.github/workflows/clang-format.yml
.github/workflows/clang-tidy-qz.yml
.github/workflows/clang-tidy-size.yml
.github/workflows/codeql-analysis.yml
.github/workflows/unit-test-qz.yml
.github/workflows/unit-test-size.yml
include/Analyzer.h
include/CDF97.h
include/SPECK_Storage.h
include/SPERR.h
include/sperr_helper.h
src/Analyzer.cpp
src/CDF97.cpp
src/CMakeLists.txt
src/SPECK2D.cpp
src/SPECK3D.cpp
src/SPECK3D_Compressor.cpp
src/SPECK3D_Decompressor.cpp
src/SPECK_Storage.cpp
src/SPERR.cpp
src/sperr_helper.cpp
utilities/probe_3d_qz.cpp
utilities/qccpack/Makefile
utilities/qccpack/example_qcc_dwt3d.c

Mostly minor changes. Experimenting with an Analyzer class that estimates the final PSNR based on quantization error of the wavelet coefficients. It's not deployed yet and more experimentation is needed.

Energy research

---

examples/C_API/3d.c
examples/C_API/test.sh
include/SPERR_C_API.h
src/SPERR_C_API.cpp
utilities/compressor_2d.cpp
utilities/compressor_3d.cpp

Investigate

---

src/SPECK_Storage.cpp
src/SPERR2D_Compressor.cpp
src/SPERR3D_Compressor.cpp

Include some headers that were missed causing build failures on newer GCC.

some fixes for newer gcc

---

include/SPERR_C_API.h
src/SPERR_C_API.cpp

This PR implements a decompression function in C API that requires a user allocated memory space.

add function sperr_decomp_user_mem

---

include/SPERR.h
src/SPERR.cpp

This PR implements an "intelligent" quantization threshold estimate. In practice it doesn't seem to have a big impact on coding efficiency though.

Outlier Coder Intelligient Threshold

---

include/SPERR.h
src/SPERR.cpp

Outlier coder improv

---

include/SPERR3D_OMP_C.h
include/SPERR3D_OMP_D.h
src/SPERR3D_OMP_C.cpp
src/SPERR3D_OMP_D.cpp
test_scripts/speck2d_unit_test.cpp
test_scripts/speck3d_unit_test.cpp

Improve header for 3D volumes

---

include/Bitstream.h
include/SPECK_INT.h
src/SPECK1D_INT_DEC.cpp
src/SPECK1D_INT_ENC.cpp
src/SPECK3D_INT_DEC.cpp
src/SPECK3D_INT_ENC.cpp
src/SPECK_INT.cpp
src/SPERR_Driver.cpp
utilities/compressor_2d.cpp
utilities/compressor_3d.cpp
utilities/mid-tread.cpp

This PR uses the custom Bitstream to act as the main bit buffer. On various platforms, the overall performance is 10% or more.

Fast bit buffer

---

include/Bitmask.h
src/Bitmask.cpp
test_scripts/bitstream_unit_test.cpp

This PR is mostly for fun: it implements the spaceship operator for the Bitmask class.

Spaceship operator on Bitmask

---

include/SPECK1D_INT.h
include/SPECK1D_INT_DEC.h
include/SPECK1D_INT_ENC.h
include/SPECK2D_INT.h
include/SPECK2D_INT_DEC.h
include/SPECK2D_INT_ENC.h
include/SPECK3D_INT.h
include/SPECK3D_INT_DEC.h
include/SPECK3D_INT_ENC.h
src/SPECK2D_INT.cpp
src/SPECK3D_INT.cpp
src/SPECK3D_INT_ENC.cpp

Some misc changes. Added the `final` keyword to virtual functions and classes, hoping to see some performance improvements, but there's hardly anything observable.

Add final keyword, misc

---

examples/C_API/2d.c
examples/C_API/3d.c
examples/C_API/Makefile
include/SPERR_C_API.h
src/SPERR_C_API.cpp
utilities/sperr2d.cpp

This PR adds an option in the `sperr_comp_2d()` C function to decide if to include a header or not.

Rich 2d meta

---

CMakeLists.txt
cli11.patch
include/SPECK1D_FLT.h
src/CMakeLists.txt
src/SPECK1D_FLT.cpp

Class `SPECK1D_FLT` is for testing and research only at this point. 
This PR also applies a patch to CLI11 so CMake doesn't issue warnings anymore.

Add experimental SPECK1D_FLT

---

README.md

Minor work on README
