- src/sperr_helper.cpp
- test_scripts/sperr_helper_unit_test.cpp
Only use strided strategy when packing, but no when unpacking... 
The speedup on packing can be close to 2X.
> use strided strategy when packing booleans

- CMakeLists.txt
- include/SPECK2D.h
- include/SPECK3D.h
- include/sperr_helper.h
- src/SPECK2D.cpp
- src/SPECK2D_Decompressor.cpp
- src/SPERR.cpp
- src/sperr_helper.cpp
- test_scripts/speck2d_unit_test.cpp
- test_scripts/speck3d_unit_test.cpp
- test_scripts/sperr_helper_unit_test.cpp
Brings multiple performance optimizations to 2D SPECK. The most significant two are:
1) Uses a list of indices, instead of sets, to represent pixels;
2) Separate encoding and decoding functions, so conditional jumps are less. 
They bring around 15% -- 20% performance improvements.
There are other minor code improvements as well.
> 2D optimization

- CMakeLists.txt
- include/SPECK2D.h
- include/SPECK3D.h
- src/SPECK2D.cpp
- src/SPECK3D.cpp
- test_scripts/speck2d_unit_test.cpp
- test_scripts/speck3d_unit_test.cpp
Changes the algorithm in fixed-size mode to have a (hopefully) big performance improvement. 
It mainly avoids the random memory access that occurs in the `refinement_pass`.
Profiler results confirm this improvement. The following graph is from VTune, where it shows the memory bandwidth utilization before and after this PR. Clearly, the program is less demanding on memory bandwidth after this PR. The runtime improvement is around 20%. 
Before PR:
After PR:
> Speedy size

- include/SPECK2D.h
- include/SPECK3D.h
- src/SPECK2D.cpp
- src/SPECK3D.cpp
which is a little slower than the old method, but allows for easier error estimation.  The QZ_TERM mode code is more similar to fixed-size code too!
> New method to implement QZ_TERM mode

- include/SPECK2D.h
- include/SPECK3D.h
- include/SPECK_Storage.h
So that SPECK2D and SPECK3D classes have much less private data members.
> move a few data structures to the SPECK_Storage base class

- include/SPECK_Storage.h
- src/SPECK2D.cpp
- src/SPECK3D.cpp
- src/SPECK_Storage.cpp
Estimate MSE at every iteration instead of when there are more than 10% coefficients being quantized.
> get rid of 10% coefficients being quantized test

- .github/workflows/clang-format.yml
- .github/workflows/clang-tidy.yml
- CMakeLists.txt
- include/SPECK_Storage.h
- include/SPERR2D_Compressor.h
- include/SPERR3D_Compressor.h
- include/SPERR3D_OMP_C.h
- include/sperr_helper.h
- src/SPECK2D.cpp
- src/SPECK3D.cpp
- src/SPECK_Storage.cpp
- src/SPERR2D_Compressor.cpp
- src/SPERR3D_Compressor.cpp
- src/SPERR3D_OMP_C.cpp
- src/sperr_helper.cpp
- test_scripts/speck2d_unit_test.cpp
- test_scripts/speck3d_unit_test.cpp
- utilities/compressor_2d.cpp
- utilities/compressor_3d.cpp
- This PR implements Peter Lindstrom's suggestion on determining an optimal quantization threshold in fixed PWE and PSNR mode. 
- It also reduces runtime memory footprint and runs a bit faster with a new RMSE estimation method. 
- Finally, it removes the `fixed qz level` compression mode.
> Better estimation of quantization threshold

- CMakeLists.txt
- This PR introduces a branch in CMakeLists.txt so that different execution paths are used for CMake version lower or higher than 3.24.
- This PR also bumps the software version to 0.3.
> update cmake script

- src/SPERR.cpp
- utilities/compressor_2d.cpp
- utilities/compressor_3d.cpp
Sets the SPERR terminal quantization threshold as the user-specified tolerance.
> Sperr q improves more

- README.md
- include/sperr_helper.h
- src/sperr_helper.cpp
- utilities/compressor_2d.cpp
- utilities/compressor_3d.cpp
This PR add Accuracy Gain output in its command line utilities, and also added a code quality badge. 
Note: gain = log2(s / E) - R, where s is the standard deviation of the original data, E is the root-mean-square error, and R is the rate in bits/value (aka. BPP).
> Accuracy gain

- src/SPECK_Storage.cpp
- test_scripts/speck2d_unit_test.cpp
- test_scripts/speck3d_unit_test.cpp
also changed the unit test a tiny bit so we don't need to worry about float/double issue in unit tests.
> implement q policy described in the paper

- CMakeLists.txt
- SPERR.pc.in
- src/CMakeLists.txt
This is needed for spack support.  Apparently we didn't get all of my fixes in when we switched from my repo to yours. I'll add explanatory comments below.  I generally tried to default to what the behavior was before I touched anything.
> allow the user to provide their own zstd dependency

- include/ZFP_bitstream.h
- include/bitstream.inl
- src/CMakeLists.txt
- src/ZFP_bitstream.cpp
- test_scripts/CMakeLists.txt
- test_scripts/bitstream_unit_test.cpp
This PR introduces `ZFP_bitstream` class, which is likely much more performant than `std::vector<bool>`. This PR will help issue #189  and #190 .
This PR doesn't put `ZFP_bitstream` in use anywhere of the coding/decoding algorithms though.
> Wrap zfp bitstream in C++ class

- include/CDF97.h
- include/Conditioner.h
- include/SPECK_Storage.h
- include/SPERR.h
- include/SPERR2D_Compressor.h
- include/SPERR2D_Decompressor.h
- include/SPERR3D_Compressor.h
- include/SPERR3D_Decompressor.h
- include/SPERR3D_OMP_D.h
- include/sperr_helper.h
- src/SPERR2D_Compressor.cpp
- src/SPERR2D_Decompressor.cpp
- src/SPERR3D_Decompressor.cpp
- src/sperr_helper.cpp
- test_scripts/dwt_unit_test.cpp
- utilities/compressor_2d.cpp
- utilities/compressor_3d.cpp
This PR simply replaces many occurrences of `std::vector<double>` with `vecd_type`. This PR is supposed to facilitate further effort to use data structures  other than `std::vector<double>`. One of the alternatives being explored right now is `kokkos::vector<double>`.
> Enforce vecd_type

- include/CDF97.h
- include/sperr_helper.h
- src/CDF97.cpp
- src/SPECK2D.cpp
- src/SPECK3D.cpp
- src/SPECK_Storage.cpp
- src/SPERR.cpp
- src/SPERR2D_Compressor.cpp
- src/SPERR2D_Decompressor.cpp
- src/SPERR3D_Compressor.cpp
- src/SPERR3D_Decompressor.cpp
- src/SPERR3D_OMP_C.cpp
- src/SPERR3D_OMP_D.cpp
- src/sperr_helper.cpp
This is a minor improvement with the addition of many `const` keyword added to iterators and a few function interfaces. 
The motivation of this work is that occasionally `const` allows more aggressive compiler optimizations.
> Const enforcement

- include/SPERR.h
- include/SPERR2D_Compressor.h
- include/SPERR2D_Decompressor.h
- include/SPERR3D_Compressor.h
- include/SPERR3D_Decompressor.h
- include/SPERR3D_OMP_C.h
- include/sperr_helper.h
- src/SPERR.cpp
- src/SPERR2D_Compressor.cpp
- src/SPERR2D_Decompressor.cpp
- src/SPERR3D_Compressor.cpp
- src/SPERR3D_Decompressor.cpp
- src/SPERR3D_OMP_C.cpp
- src/SPERR3D_OMP_D.cpp
- test_scripts/sperr_helper_unit_test.cpp
Use `vec_type` in more places. Also identified an error when assigning to a `kokkos::vector`, and also found a workaround.
> More vec type

- include/Bitmask.h
- include/Bitstream.h
- include/SPECK1D_INT_DEC.h
- include/SPECK1D_INT_ENC.h
- include/SPECK3D_INT.h
- include/SPECK3D_INT_DEC.h
- include/SPECK3D_INT_ENC.h
- include/SPECK_INT.h
- include/SPERR_Driver.h
- include/sperr_helper.h
- include/zfp_bitstream.h
- src/Bitmask.cpp
- src/Bitstream.cpp
- src/CMakeLists.txt
- src/SPECK1D_INT_DEC.cpp
- src/SPECK1D_INT_ENC.cpp
- src/SPECK3D_INT.cpp
- src/SPECK3D_INT_DEC.cpp
- src/SPECK3D_INT_ENC.cpp
- src/SPECK_INT.cpp
- src/SPERR3D.cpp
- src/SPERR_Driver.cpp
- src/sperr_helper.cpp
- src/zfp_bitstream.c
This PR introduces a custom bitmask, Bitmask, and uses it for storage of data structure `m_LSP_mask`. Experiments show that this bitmask improves the runtime significantly across all platforms tested.
This PR also moves refinement pass implementation to the base SPECK_INT class.
> Custom bitmask for m_LSP_mask

- include/SPECK_FLT.h
- include/SPECK_INT.h
- include/SPERR3D_OMP_C.h
- src/SPECK_FLT.cpp
- src/SPECK_INT.cpp
- src/SPERR3D_OMP_C.cpp
- test_scripts/speck2d_flt_unit_test.cpp
- utilities/double_prec.cpp
- utilities/sperr2d.cpp
- utilities/sperr3d.cpp
- utilities/sperr3d_trunc.cpp
This PR implements one approach to achieve fixed-rate compression; call it max integer approach.
Using this approach, wavelet coefficients are quantized to a very big integer, and then the integers go through the standard SPECK_INT encoding. The idea is that the integers are big enough that the SPECK_INT coding won't finish before we exhaust the prescribed bit budget.
The pro of this approach is that it makes use of the SPECK_INT code. The con is that given a certain bitrate, it achieves 2--4dB lower accuracy than the current main branch. I suspect that it's because of floating point rounding errors when two operands are too many magnitudes different. Anyway, I'll bring in this implementation first, and then do more investigation.
> One approach to achieve fixed-rate compression

- include/SPECK2D_INT_DEC.h
- include/SPECK_FLT.h
- include/SPECK_INT.h
- src/SPECK1D_INT_DEC.cpp
- src/SPECK2D_INT_DEC.cpp
- src/SPECK3D_INT_DEC.cpp
- src/SPECK_FLT.cpp
- src/SPECK_INT.cpp
- test_scripts/bitstream_unit_test.cpp
- test_scripts/speck2d_flt_unit_test.cpp
- test_scripts/sperr3d_omp_unit_test.cpp
This PR improves the SPECK integer decoding so that during partial decoding (e.g., progressive access or fixed-rate compression) the reconstruction value is at the center of an interval. It improves accuracy gain in those cases.
> Improved progressive decoding

- src/SPECK3D_INT_ENC.cpp
This PR manually handles 4-element and 8-element cases (instead of relying on recursion) when creating morton organization, so it reduces the number of recursions and also the invocation of dividing sets. It's another obvious performance improvement.
> Less recursions when depositing morton

- include/Bitmask.h
- include/Bitstream.h
- include/SPECK2D_INT.h
- include/SPECK_FLT.h
- include/SPECK_INT.h
- include/SPERR3D_OMP_C.h
- src/SPECK1D_INT.cpp
- src/SPECK2D_INT.cpp
- src/SPECK3D_INT.cpp
- src/SPECK_INT.cpp
This PR changes the order of data members declared in a few classes. As a result, the size of a class reduced by 8 bytes or 16 bytes in a few of them.
> change class layout

- include/Bitmask.h
- src/Bitmask.cpp
- test_scripts/bitstream_unit_test.cpp
The `has_true()` function now takes in a template parameter, which controls how much information the return value contains. Of course, there's a tradeoff between performance and the amount of information returned.
> finish improved has_true() function

- src/SPECK1D_INT_DEC.cpp
- src/SPECK1D_INT_ENC.cpp
- src/SPECK2D_INT.cpp
- src/SPECK3D_INT.cpp
- src/SPECK_FLT.cpp
- src/SPECK_INT.cpp
This PR removes a lot of empty loops in refinement passes.
It provides a consistent but modest performance improvement.
It also makes the code a lot cleaner.
> use countr_zero

- include/Bitmask.h
- src/Bitmask.cpp
- src/SPECK1D_INT_DEC.cpp
- src/SPECK1D_INT_ENC.cpp
- src/SPECK2D_INT.cpp
- src/SPECK3D_INT.cpp
- src/SPECK_INT.cpp
- test_scripts/bitstream_unit_test.cpp
I found that c++ feature check macros, at least `__cpp_lib_bitops`, was not quite reliable.
> Use __cplusplus version check, and minor improve on the bitmask.
